baseURL: http://acme.johnackley.com
languageCode: en-us
title: ACME Corp
theme: github.com/hugoinaction/Eclectic
publishDir: docs
author:
  email: "john@johnackley.com"
  name: "John Ackley"

menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 1
    - identifier: contact
      name: Contact
      url: /contact
      weight: 2

params:
  color: "#B14130"
  copyright: "Copyright &copy; 2020 John Ackley LLC"
  footer:
    - title: About
      content: John Ackley LLC is the builder of fine websites.
    - title: Recent News
      recents: blog
      recentCount:  7
    - title: Contact Us
      contact: true